version: '3.8'

services:
  # Proposers (com um sendo líder)
  proposer1:
    build:
      context: ./proposer
    image: proposer1
    hostname: proposer1
    environment:
      - NODE_ID=1
      - NODE_ROLE=proposer
      - PORT=3001
    ports:
      - "3001:3001"
      - "8001:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - discovery

  proposer2:
    build:
      context: ./proposer
    image: proposer2
    hostname: proposer2
    environment:
      - NODE_ID=2
      - NODE_ROLE=proposer
      - PORT=3002
    ports:
      - "3002:3002"
      - "8002:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - discovery

  proposer3:
    build:
      context: ./proposer
    image: proposer3
    hostname: proposer3
    environment:
      - NODE_ID=3
      - NODE_ROLE=proposer
      - PORT=3003
    ports:
      - "3003:3003"
      - "8003:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - discovery

  # Acceptors
  acceptor1:
    build:
      context: ./acceptor
    image: acceptor1
    hostname: acceptor1
    environment:
      - NODE_ID=4
      - NODE_ROLE=acceptor
      - PORT=4001
    ports:
      - "4001:4001"
      - "8004:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - discovery

  acceptor2:
    build:
      context: ./acceptor
    image: acceptor2
    hostname: acceptor2
    environment:
      - NODE_ID=5
      - NODE_ROLE=acceptor
      - PORT=4002
    ports:
      - "4002:4002"
      - "8005:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - discovery

  acceptor3:
    build:
      context: ./acceptor
    image: acceptor3
    hostname: acceptor3
    environment:
      - NODE_ID=6
      - NODE_ROLE=acceptor
      - PORT=4003
    ports:
      - "4003:4003"
      - "8006:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - discovery

  # Learners
  learner1:
    build:
      context: ./learner
    image: learner1
    hostname: learner1
    environment:
      - NODE_ID=7
      - NODE_ROLE=learner
      - PORT=5001
    ports:
      - "5001:5001"
      - "8007:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - discovery

  learner2:
    build:
      context: ./learner
    image: learner2
    hostname: learner2
    environment:
      - NODE_ID=8
      - NODE_ROLE=learner
      - PORT=5002
    ports:
      - "5002:5002"
      - "8008:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - discovery

  # Clients
  client1:
    build:
      context: ./client
    image: client1
    hostname: client1
    environment:
      - NODE_ID=9
      - NODE_ROLE=client
      - PORT=6001
    ports:
      - "6001:6001"
      - "8009:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - discovery

  client2:
    build:
      context: ./client
    image: client2
    hostname: client2
    environment:
      - NODE_ID=10
      - NODE_ROLE=client
      - PORT=6002
    ports:
      - "6002:6002"
      - "8010:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - discovery

  # Discovery Service
  discovery:
    build:
      context: ./discovery
    image: discovery
    hostname: discovery
    environment:
      - PORT=7000
    ports:
      - "7000:7000"
      - "8000:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  paxos-network:
    driver: overlay